spring.application.name=login-service

---

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: santoshpulichinthala
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 9092